language: node_js
node_js:
- node

install:
- npm install

before_script: 
  chmod +x ./deploy.sh
script: 

deploy:
- provider: surge
  skip_cleanup: true
  project: "./src/"
  domain: nak-sued-print-cal.surge.sh
  on:
    branch: develop
- provider: script
  skip_cleanup: true
  script: ./deploy.sh
